# Generated by Django 4.2.1 on 2023-05-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadFiscalizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('detalle_link', models.URLField()),
                ('unidad_fiscalizable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snifa.unidadfiscalizable')),
            ],
            options={
                'verbose_name_plural': 'sanciones',
            },
        ),
    ]
